[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_routing = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
fee_routing = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet]
fee_routing = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"

[[test.validator.clone]]
address = "strmRqUCoQUgGUan5YhzUZa6KqdzwX5L6FpUxfmKg5m"
