[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_routing = "RECTGNmLAQ3jBmp4NV2c3RFuKjfJn2SQTnqrWka4wce"

[programs.devnet]
fee_routing = "RECTGNmLAQ3jBmp4NV2c3RFuKjfJn2SQTnqrWka4wce"

[programs.mainnet]
fee_routing = "RECTGNmLAQ3jBmp4NV2c3RFuKjfJn2SQTnqrWka4wce"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=142fb48a-aa24-4083-99c8-249df5400b30"

[[test.validator.clone]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"

[[test.validator.clone]]
address = "strmRqUCoQUgGUan5YhzUZa6KqdzwX5L6FpUxfmKg5m"
