[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[programs.devnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[programs.mainnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator]
url = "https://api.devnet.solana.com"

# Clone external programs from devnet for local testing
[[test.validator.clone]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"  # Meteora CP-AMM

[[test.validator.clone]]
address = "strmRqUCoQUgGUan5YhzUZa6KqdzwX5L6FpUxfmKg5m"  # Streamflow
