[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[programs.devnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[programs.mainnet]
fee_routing = "RECtHTwPBpZpFWUS4Cv7xt2qkzarmKP939MSrGdB3WP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000

[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=142fb48a-aa24-4083-99c8-249df5400b30"

# Clone external programs from devnet for local testing
# Meteora CP-AMM (program + programData for upgradeable program)
[[test.validator.clone]]
address = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"  # CP-AMM Program

[[test.validator.clone]]
address = "AUh8bm2XsMfex3KjYGcM3G4uBqUNSDw6HEhWaWMYnyPH"  # CP-AMM ProgramData

[[test.validator.clone]]
address = "8CNy9goNQNLM4wtgRw528tUQGMKD3vSuFRZY2gLGLLvF"  # CP-AMM Config (index 0)

# Streamflow (program + programData for upgradeable program)
[[test.validator.clone]]
address = "strmRqUCoQUgGUan5YhzUZa6KqdzwX5L6FpUxfmKg5m"  # Streamflow Program

[[test.validator.clone]]
address = "796tZf2QrH1ebZTQC1mDHYP6weDqSKuqbeyaXd64Prs"  # Streamflow ProgramData

